version: '3'
services:
    theark:
        build:
            context: ./
            dockerfile: Dockerfile_Ark
        container_name: 'theark'
        network_mode: 'host'
        privileged: true
        environment:
            - ARK_LISTEN_IP=127.0.0.1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
            interval: '10s'
            timeout: '10s'
            retries: 5
    sangheili:
        build: 'sangheili/'
        container_name: 'sangheili'
        network_mode: 'host'
        privileged: true
        restart: on-failure
        depends_on:
            - theark
    proxy:
        build: 'proxy/'
        network_mode: 'host'
