version: '3'
services:
    theark:
        build: https://github.com/ritredteam/theark.git
        network_mode: 'host'
        privileged: true
        environment:
            - FLASK_DEBUG=false
            - FLASK_PORT=5000
            - ARK_DATABASE=./db/theark.sqlite
        volumes:
            - ./arkdb:/opt/theark/db/
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0/"]
            interval: '10s'
            timeout: '10s'
            retries: 5
    sangheili:
        build: 'sangheili/'
        network_mode: 'host'
        privileged: true
        environment:
            - address_server=http://theark
            - reserve_addresses=True
            - address_count=50
        restart: on-failure
        depends_on:
            - theark